### ISSUE TITLE
Instructions pulled in Debian's syncthing instead of Syncthing's syncthing

### ISSUE THREAD

**Issue by genpfault** [syncthing/apt-web#13]
Just tried the instructions on [the landing page](https://apt.syncthing.net) and the final install command:

    sudo apt-get install syncthing

...pulled in [Debian's `0.14.51+ds2-3`](https://packages.debian.org/buster/syncthing) instead of Syncthing's `0.14.51`.  I guess because Debian's version is "greater" somehow?  Unfortunately Debian's version has broken icon fonts :(

Using `-t syncthing` pulled in the correct version and fixed the font issue for me:

    sudo apt-get install -t syncthing syncthing

Syncthing Version: v0.14.51
OS Version: Debian 10/Buster/testing (amd64), up-to-date as of today
Browser Version: Firefox 62.0.3

**Comment by canton7** [comment]
>  Unfortunately Debian's version has broken icon fonts :(

(See [here](https://github.com/syncthing/syncthing/pull/5237) and [here](https://github.com/syncthing/syncthing/issues/5236) and [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902981#76) for details -- the long and the short of it is that it should be fixed soon).

**Comment by imsodin** [comment]
The `-t` thingy is not enough, because a subsequent upgrade would then install the most recent version again. Really the only permanent solution (that I know) is setting the priority of the syncthing repo higher (using apt preferences config files). We could suggest to write the following into `/etc/apt/preferences.d/syncthing`:

```
Package: *syncthing*
Pin: origin apt.syncthing.net
Pin-Priority: 900

Package: *syncthing*
Pin: origin *
Pin-Priority: 100
```

However that's exposing lots of unsuspecting users to the can of worms that is apt_preferences...

An alternative is to make users aware, that there are packages in the main repo, and they should only use syncthing's repo if they want RCs or have another good reason (if you don't want RCs, the delay in releases is small enough nowadays that I wouldn't count being up-to-date as an important reason anymore).

**Comment by calmh** [comment]
I guess that depends on which Debian you’re following? So currently the Debian shipped version is (cosmetically) broken, but otherwise they’re usually supposed to be equivalent and it doesn’t matter which one is used so long as it’s a modern version.  So in the grand scheme of things, adding our repo should be safe and work as expected, if the expectation is to get a modern Syncthing that works. Sometimes we will be ahead, sometimes Debian will be, but the result is similar. 

For other Debians like Ubuntu that don’t do rolling updates our version will always be newer.

**Comment by aviau** [comment]
If I changed my versioning to use ~ instead of + then maybe we wouldn't have this problem at all.

**Comment by calmh** [comment]
Tilde would indeed be neat as they would then sort as lesser than the prefix-less package. (We do tilde for the RC:s etc, for this reason.)

**Comment by aviau** [comment]
It is too late for 0.14.54 as I already uploaded 0.14.54+ds1-1. However I will do it for 0.14.55.

**Comment by calmh** [comment]
Awesome

**Comment by aviau** [comment]
Done. I have uploaded syncthing 1.0.0~ds1-1 to Debian today.
