### ISSUE TITLE
The work of debian repositories on HTTP

### ISSUE THREAD

**Issue by Ratio2** [syncthing/apt-web#27]
Some HTTPS traffic is blocked in my country (probably due to HTTPS extensions).

It would be nice to make debian repositories work through HTTP, since they are still checked for integrity by the package manager.
```
$ curl https://download.virtualbox.org/virtualbox/debian
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
...

$ curl https://syncthing.net
<!DOCTYPE html>
...

$ curl https://apt.syncthing.net
curl: (28) Failed to connect to apt.syncthing.net port 443: Connection timed out

$ curl http://apt.syncthing.net
Moved Permanently
```

**Comment by calmh** [comment]
Yeah this used to work, but I moved it around a bit and now it's HTTPS only apparently. I'll see if I can fix that.

**Comment by Ratio2** [comment]
Same problem for https://relays.syncthing.net/endpoint
```
dynamic+https://relays.syncthing.net/endpoint: Get "https://relays.syncthing.net/endpoint": dial tcp 143.244.196.6:443: i/o timeout
```

Only https://syncthing.net/ works

**Comment by calmh** [comment]
Relays have never been available over http though.

**Comment by Ratio2** [comment]
I understand that relays have always been available only via HTTPS. But it will not be superfluous to have access to them also via HTTP. This will add flexibility, and there are no shortcomings at first glance.

relays.syncthing.net and apt.syncthing.net are at the same address, possibly on the same server.

This will solve my specific problem with HTTPS blocking, maybe it will help someone else in the future.

**Comment by calmh** [comment]
To be honest, your specific issue with your government blocking HTTPS left and right isn't something I really care about enough to put effort into fixing, especially when HTTPS is generally speaking much superior to HTTP in all cases. There is, perhaps, a case to be made for apt.syncthing.net specifically to be available over HTTP because it's traditional for Debian archives to use HTTP and, historically, some of the tooling didn't work out of the box with HTTPS.

This is not a reason to HTTP-enable other services that have always been HTTPS and really should stay HTTPS.
