### ISSUE TITLE
Debian installation instructions store keyring in wrong directory

### ISSUE THREAD

**Issue by dhs-rec** [syncthing/apt-web#28]
The instructions tell users to install the keyring file into `/usr/share/keyrings`. But, according to [this Debian wiki page](https://wiki.debian.org/DebianRepository/UseThirdParty), keyrings should only be stored in this directory if there is also a package that manages them going forward. However, there doesn't seem to be such a package, so the keyring file should be stored into `/etc/apt/keyrings` instead. Please either correct the instructions or provide a package for managing the keyring file.

**Comment by acolomb** [comment]
Thank you very much for the pointer to that wiki page.  Indeed very useful to have some "official" guidelines available, which used to be incomplete and contradicting for historic reasons.

Making a `syncthing-archive-keyring` package should not be very hard, but I guess there's no one currently willing to work on it.  If you can, don't hesitate to take a stab at it yourself.  Otherwise, I guess we're stuck with the `/etc/apt/keyrings` recommendation.

Some other things currently different from the recommendations:

1. IIUC, https://apt.syncthing.net/syncthing-archive-keyring.gpg should exist, but we have a different URL in the instructions.
2. The "suite" and "component" parts seem to be mixed up compared to what Debian recommends. it should be `stable/main` instead of current `syncthing/stable`.
3. The preferences file snippet should be `/etc/apt/preferences.d/syncthing.pref`, we are currently missing the `.pref` extension.
4. For the sources file it is recommended to use the more verbose Deb822 format.  I'd disagree with that though, as it's much harder to give a one-line copy-and-paste example, and more tedious to type manually.

You're very welcome to make a Pull Request for your suggested change and maybe no. 3 above, if you feel like you're up to the task.

**Comment by dhs-rec** [comment]
I'll see what I can do reg. the `.pref` extension.

I'd disagree with your disagreement about `deb822` though, given that it will become the default in future Debian versions and Ubuntu will do the switch with the upcoming 23.10 already.

**Comment by acolomb** [comment]
> I'd disagree with your disagreement about `deb822` though, given that it will become the default in future Debian versions and Ubuntu will do the switch with the upcoming 23.10 already.

But does it work for older distros as well?  Where is the cut-off point for Debian, Ubuntu and other derivatives?  I tend to be quite conservative here as long as the old way still works fine in modern distros.

**Comment by dhs-rec** [comment]
Yes, it should work in Debian versions starting from Jessie (8).

**Comment by imsodin** [comment]
Not that I care much either way, but it's not even a recommendation in that doc:

> The "Deb822" file format MAY be used instead to improve clarity for complex entries (e.g. deriv.sources).

**Comment by dhs-rec** [comment]
That's correct, `deb822` is not a recommendation. Nevertheless will it become the default format in upcoming Debian and Ubuntu versions.

**Comment by acolomb** [comment]
> I also don't see anything regarding point 1 (there's just an example with such a url).

Quoting from [that page](https://wiki.debian.org/DebianRepository/UseThirdParty#OpenPGP_certificate_distribution), the file name is a SHOULD recommendation:

> A binary export (gpg --export) of the certificate SHOULD be available at the root of the repository under the filename deriv-archive-keyring.pgp, where deriv is the a short name for the repository.
